# Generated by Django 2.1.7 on 2019-09-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
