# Generated by Django 2.1.7 on 2019-09-30 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
