# Generated by Django 2.1.7 on 2019-10-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
